environment:
  env_id: LunarLander-v3
  continuous: true
demo:
  max_steps: 2000
training:
  target_score: 200
  max_timesteps: 2000000
  learning_rate: 0.0003
  policy_net:
  - 128
  - 128
  eval_freq: 10000
