environment:
  env_id: 'BipedalWalker-v3'

demo:
  max_steps: 2000

algorithms:
  ppo:
    target_score: 300
    max_timesteps: 2000000
    learning_rate: 0.0003
    policy_net: [256,256]
    eval_freq: 5000

  sac:
    target_score: 300
    max_timesteps: 1000000
    learning_rate: 0.0001
    policy_net: [400,300]
    eval_freq: 5000
    batch_size: 256
    buffer_size: 300000
    learning_starts: 10000
    tau: 0.005
    gamma: 0.99
    train_freq: 1
    gradient_steps: 1

  a2c:
    target_score: 300
    max_timesteps: 2000000
    learning_rate: 0.0007
    policy_net: [256,256]
    eval_freq: 10000
    n_steps: 5
    gamma: 0.99
    gae_lambda: 1.0
    ent_coef: 0.0
    vf_coef: 0.5
    max_grad_norm: 0.5
    rms_grad_eps: 1e-5
    use_rms_prop: true
    normalize_advantage: false