environment:
  env_id: 'CartPole-v1'

demo:
  max_steps: 1500

algorithms:
  ppo:
    target_score: 475
    max_timesteps: 2000000
    learning_rate: 0.0003
    policy_net: [128,128]
    eval_freq: 10000

  sac:
    target_score: 475

  dqn:
    target_score: 475
    max_timesteps: 500000
    learning_rate: 0.0001
    policy_net: [128,128]
    eval_freq: 10000
    batch_size: 32
    buffer_size: 100000
    learning_starts: 50000
    tau: 1.0
    gamma: 0.9
    train_freq: 4
    gradient_steps: 1
    target_update_interval: 10000
    exploration_fraction: 0.1
    exploration_initial_eps: 1.0
    exploration_final_eps: 0.05

  a2c:
    target_score: 475
    max_timesteps: 1000000
    learning_rate: 0.0007
    policy_net: [128,128]
    eval_freq: 10000
    n_steps: 5
    gamma: 0.99
    gae_lambda: 1.0
    ent_coef: 0.0
    vf_coef: 0.5
    max_grad_norm: 0.5
    rms_grad_eps: 1e-5
    use_rms_prop: true
    normalize_advantage: false