environment:
  env_id: 'MountainCar-v0'

demo:
  max_steps: 1000

algorithms:
  ppo:
    target_score: -110
    max_timesteps: 1000000
    learning_rate: 0.0003
    policy_net: [64, 64]
    eval_freq: 10000
    n_steps: 2048
    batch_size: 64
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.98
    clip_range: 0.2
    ent_coef: 0.0

  dqn:
    target_score: -110
    max_timesteps: 1000000
    learning_rate: 0.0001
    policy_net: [256, 256]
    eval_freq: 10000
    batch_size: 128
    buffer_size: 100000
    learning_starts: 1000
    tau: 1.0
    gamma: 0.99
    train_freq: 4
    gradient_steps: 1
    target_update_interval: 600
    exploration_fraction: 0.7
    exploration_initial_eps: 1.0
    exploration_final_eps: 0.05

  a2c:
    target_score: -110
    max_timesteps: 1000000
    learning_rate: 0.0007
    policy_net: [64, 64]
    eval_freq: 10000
    n_steps: 5
    gamma: 0.99
    gae_lambda: 1.0
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
    rms_prop_eps: 1e-5
    use_rms_prop: true
    normalize_advantage: false