environment:
  env_id: 'Pendulum-v1'

demo:
  max_steps: 600

algorithms:
  ppo:
    target_score: -120
    max_timesteps: 2000000
    learning_rate: 0.0003
    policy_net: [128,128]
    eval_freq: 10000

  sac:
    target_score: 300