environment:
  env_id: 'Pendulum-v1'

demo:
  max_steps: 600

algorithms:
  ppo:
    target_score: -120
    max_timesteps: 2000000
    learning_rate: 0.0003
    policy_net: [128,128]
    eval_freq: 10000

  sac:
    target_score: -120
    max_timesteps: 50000
    learning_rate: 0.001
    policy_net: [256,256]
    eval_freq: 2000
    learning_starts: 1000
    batch_size: 256
    buffer_size: 50000
    gradient_steps: 1
    tau: 0.005
    gamma: 0.99
    train_freq: 1

  a2c:
    target_score: -120
    max_timesteps: 1000000
    learning_rate: 0.0007
    policy_net: [128,128]
    eval_freq: 5000
    n_steps: 5
    gamma: 0.99
    gae_lambda: 1.0
    ent_coef: 0.0
    vf_coef: 0.5
    max_grad_norm: 0.5
    rms_grad_eps: 1e-5
    use_rms_prop: true
    normalize_advantage: false

  td3:
    target_score: -120
    max_timesteps: 50000
    learning_rate: 0.001
    policy_net: [256,256]
    eval_freq: 2000
    batch_size: 100
    buffer_size: 200000
    learning_starts: 10000
    tau: 0.005
    gamma: 0.99
    train_freq: 1
    gradient_steps: -1
    policy_delay: 2
    target_policy_noise: 0.2
    target_noise_clip: 0.5