environment:
  env_id: Walker2DBulletEnv-v0
demo:
  max_steps: 2000
training:
  target_score: 2500
  max_timesteps: 1000000
  learning_rate: 0.001
  policy_net:
  - 400
  - 300
  eval_freq: 5000
  batch_size: 100
  buffer_size: 1000000
  learning_starts: 10000
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: -1
  policy_delay: 2
  target_policy_noise: 0.2
  target_noise_clip: 0.5
