environment:
  env_id: Pendulum-v1
demo:
  max_steps: 600
training:
  target_score: -120
  max_timesteps: 50000
  learning_rate: 0.001
  policy_net:
  - 256
  - 256
  eval_freq: 2000
  batch_size: 128
  buffer_size: 200000
  learning_starts: 1000
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: -1
  noise_type: normal
  noise_sigma: 0.1
