environment:
  env_id: HalfCheetahBulletEnv-v0
demo:
  max_steps: 2000
training:
  target_score: 2000
  max_timesteps: 2000000
  learning_rate: 0.0003
  policy_net:
  - 256
  - 256
  eval_freq: 10000
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
