environment:
  env_id: CartPole-v1
demo:
  max_steps: 1500
training:
  target_score: 475
  max_timesteps: 1000000
  learning_rate: 0.0007
  policy_net:
  - 128
  - 128
  eval_freq: 10000
  n_steps: 5
  gamma: 0.99
  gae_lambda: 1.0
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  rms_grad_eps: 1e-5
  use_rms_prop: true
  normalize_advantage: false
