environment:
  env_id: Walker2DBulletEnv-v0
demo:
  max_steps: 2000
training:
  target_score: 2500
  max_timesteps: 1000000
  learning_rate: 0.0003
  policy_net:
  - 256
  - 256
  eval_freq: 5000
  batch_size: 256
  buffer_size: 300000
  learning_starts: 10000
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
